/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * Snippets API
 * Test description
 * OpenAPI spec version: v1
 */
export interface Cycle {
  action_description?: string;
  category?: number;
  check_description?: string;
  created_at?: string;
  do_description?: string;
  readonly id?: number;
  plan_description?: string;
  problem_description?: string;
  status?: string;
  title?: string;
  updated_at?: string;
}

